### ISSUE TITLE
Storing passwords/pin on cloud

### ISSUE THREAD

**Issue by 0xae** [wavesplatform/WavesWallet-android#4]
Hi why is the wallet storing passwords on [firebase](https://github.com/wavesplatform/WavesWallet-android/blob/6fcd678b99ec0cf4444d3561d1f8617c8cdeede6/app/src/main/java/com/wavesplatform/wallet/data/services/PinStoreService.java#L22) ?
I think it would be better to store them offline on the wallet data directory itself, isnt it safer?

**Comment by koloale** [comment]
Hi! Passwords aren't stored on firebase only pin codes and random keys which used to encrypt the wallet password, stored on your phone. It's the most secure methods now available, because it allows restricting pin failed attempts up to 3 times. Without firebase it's was impossible to securely use pin codes (which are 4 digits), as they would be easily brute forced.
